### ISSUE TITLE
Captcha displays before the form

### ISSUE THREAD

**Issue by solracsf** [BkrBkr/AuthCaptchaForJoomla#2]
Is it possible to display it **after** the password input field?

![image](https://user-images.githubusercontent.com/12234510/108043243-2d4ae400-7041-11eb-955d-9a9a3a32eb49.png)

**Comment by BkrBkr** [comment]
Hi unfortunately this problem seems to be related to your joomla template. Joomla itself has no option to add content to the administrator login form, so I have to determine the correct position with a regular expression. Unfortunately this is not working with your template. If you could send me the link to your website, I'll have a look at it. If you are able to alter your joomla template I could add support for a placeholder. Than you could add the placeholder to your template and define the correct position by yourself.

**Comment by BkrBkr** [comment]
You could try the new release 1.0.1 (from the release page). When you add {authCaptchaPlaceholder} within your login form html the captcha should appear at the desired position. The tag has to be within the html \<form> element. 

I'm looking forward for your feedback.

**Comment by solracsf** [comment]
Thanks, I'll try it next week.

**Comment by solracsf** [comment]
All good when using `{authCaptchaPlaceholder}` thanks 👍

**Comment by solracsf** [comment]
@BkrBkr similar thing happens in admin form if the website is multi-language within the Isis template. This should maybe be fixed with your regex as we're talking about a default template.

It should be displayed after the language drop-down.

![image](https://user-images.githubusercontent.com/12234510/108623392-2c4df400-743f-11eb-849f-12be2ac6efff.png)

**Comment by BkrBkr** [comment]
I think this is more a matter of taste than a bug. But you should be able to choose the position with the placeholder. Im looking forward to help you if this doesn't work.

**Comment by solracsf** [comment]
Ok, for me a captcha always come just before the Submit button, but if you're ok with that, i am too as i can fix it on my side 😉
